title: <p align="center"> Padmavathi Dinakaran </p>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/padmavathi-d-aa4963177/">LinkedIn</a> |
  <a href="https://github.com/Padma-aishu">GitHub</a>
 
  <br>  
  Data Science Enthusiast
  <br>
  </p>



theme: jekyll-theme-minimal
